version: '2'
services:
  kafka-server:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka-server:9092
      
    depends_on:
      - zookeeper-server
  zookeeper-server:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  namenode:
    build: ./hdfs
    image: hdfsnamenode
    container_name: namenode
    environment:
        - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
        - CLUSTER_NAME=hadooptest
    ports:
        - "9870:9870"
        - "9000:9000"
    volumes:
    - D:/PROJECTS/hadoopspark:/opt/hadoopspark
    
  datanode:
        build: ./hdfs/datanode
        image: hdfsdatanode
        container_name: datanode
        environment:
            - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
        volumes:
            - D:/PROJECTS/hadoopspark:/opt/hadoopspark

  core1:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=CORE
      - NEO4J_causalClustering_discoveryAdvertisedAddress=core1:5000
      - NEO4J_causalClustering_transactionAdvertisedAddress=core1:6000
      - NEO4J_causalClustering_raftAdvertisedAddress=core1:7000
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_causal__clustering_disable__middleware__logging=false

  core2:
    image: neo4j:latest
    ports:
      - "7475:7474"
      - "7689:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=CORE
      - NEO4J_causalClustering_discoveryAdvertisedAddress=core2:5000
      - NEO4J_causalClustering_transactionAdvertisedAddress=core2:6000
      - NEO4J_causalClustering_raftAdvertisedAddress=core2:7000
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_causalClustering_refuseToBeLeader=true

  core3:
    image: neo4j:latest
    ports:
      - "7476:7474"
      - "7690:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=CORE
      - NEO4J_causalClustering_discoveryAdvertisedAddress=core3:5000
      - NEO4J_causalClustering_transactionAdvertisedAddress=core3:6000
      - NEO4J_causalClustering_raftAdvertisedAddress=core3:7000
      - NEO4J_causalClustering_expectedCoreClusterSize=3
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000
      - NEO4J_causalClustering_refuseToBeLeader=true



  readreplica1:
    image: neo4j:latest
    ports:
      - "7477:7477"
      - "7691:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_memory_pagecache_size=10M
      - NEO4J_dbms_memory_heap_initial__size=10M
      - NEO4J_AUTH=neo4j/neo
      - NEO4J_dbms_mode=READ_REPLICA
      - NEO4J_causalClustering_discoveryAdvertisedAddress=readreplica1:5000
      - NEO4J_causalClustering_transactionAdvertisedAddress=readreplica1:6000
      - NEO4J_causalClustering_raftAdvertisedAddress=readreplica1:7000
      - NEO4J_causalClustering_initialDiscoveryMembers=core1:5000,core2:5000,core3:5000

  Producer:
    build: ./Producer
    image: andmalwerstr:latest
    container_name: andmalwerstr
    environment:
        - SPARK_MASTER_NAME=spark-master
        - SPARK_MASTER_PORT=7077
        - SPARK_APPLICATION_ARGS=foo
        - SPARK_APPLICATION_PYTHON_LOCATION=/app/app.py
        - MALWER_DATA=hdfs://namenode:9000/dataset/hadoopspark/*.csv
        - ENABLE_INIT_DAEMON=false
    links:
        - spark-master

  App:
    build: ./App
    image: appe:latest
    container_name: App
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    links:
      - kafka-server #allows spark notebook to discover kafka service by name "kafka-server"
      
    volumes:
      - ../notebooks:/home/jovyan/work/notebooks/
      
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
